[project]
name = "api.letsbuilda.dev"
description = "Public API for our projects"
authors = [
    { name = "Bradley Reynolds", email = "bradley.reynolds@darbia.dev" },
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "dependencies", "optional-dependencies"]

[project.urls]
repository = "https://github.com/letsbuilda/api.letsbuilda.dev/"
documentation = "https://docs.letsbuilda.dev/api.letsbuilda.dev/"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic.version]
attr = "api.__version__"

[tool.setuptools.dynamic.dependencies]
file = ["requirements/requirements.txt"]

[tool.setuptools.dynamic.optional-dependencies]
dev = { file = ["requirements/requirements-dev.txt"] }
tests = { file = ["requirements/requirements-tests.txt"] }
docs = { file = ["requirements/requirements-docs.txt"] }

[tool.black]
target-version = ["py310"]
line-length = 120

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "tests -r a -v --doctest-modules src"

[tool.ruff]
line-length = 120

[tool.pylint.messages_control]
disable = "C0103,R0903,E0213"
# justifications:
# C0103 (invalid-name) - pydantic
# R0903 (too-few-public-methods) - models
# E0213 (no-self-argument) - pydantic
