name: "Docker Build and Push"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio.
  id-token: write

jobs:
  build-push:
    uses: darbiadev/.github/.github/workflows/docker-build-push.yaml@main

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: "Update deployment"
        run: curl -X POST '${{ secrets.DEPLOY_WEBHOOK }}'
